import "./globals.css";

export const metadata = {
  title: "Genios Club",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="bg-[#14000b]">{children}</body>
    </html>
  );
}
